# Generated by Django 6.0.2 on 2026-02-09 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(default='voluntario', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('autenticacion_2fa_habilitada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_verificacion_correo', models.DateTimeField(blank=True, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso especial de permanencia'), ('PAS', 'Pasaporte')], default='CC', max_length=10)),
                ('numero_identificacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('intereses', models.JSONField(blank=True, default=list)),
                ('habilidades', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('cupos_disponibles', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('finalizada', 'Finalizada')], default='abierta', max_length=20)),
                ('habilidades_requeridas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.ForeignKey(db_column='id_usuario_creador', on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'convocatoria',
                'managed': True,
            },
        ),
    ]
