# Generated by Django 6.0.2 on 2026-02-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='habilidades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='intereses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='rol',
            field=models.CharField(default='voluntario', max_length=20),
        ),
    ]
