# Generated by Django 6.0.2 on 2026-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriamodel',
            name='categorias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='convocatoriamodel',
            name='horario',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='disponibilidad',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
