# Generated by Django 6.0.2 on 2026-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_convocatoriamodel_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriamodel',
            name='link_whatsapp',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='convocatoriamodel',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
