# Generated by Django 6.0.2 on 2026-02-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_usuariomodel_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=10),
        ),
    ]
