# Generated by Django 6.0.2 on 2026-02-14 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_convocatoriamodel_link_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_impacto', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_objetivo', models.BigIntegerField(blank=True, null=True)),
                ('fecha_fin', models.DateField()),
                ('recaudo_actual', models.BigIntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('objetivos', models.JSONField(blank=True, default=list)),
                ('galeria_imagenes', models.JSONField(blank=True, default=list)),
                ('permite_donacion_monetaria', models.BooleanField(default=True)),
                ('permite_donacion_especie', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campana',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
