# Generated by Django 6.0.2 on 2026-02-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_usuariomodel_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso especial de permanencia'), ('PAS', 'Pasaporte')], default='CC', max_length=10),
        ),
    ]
