# Generated by Django 6.0.2 on 2026-02-15 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_campanamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanamodel',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campanamodel',
            name='necesidades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
