# Generated by Django 6.0.2 on 2026-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_campanamodel_fecha_inicio_campanamodel_necesidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanamodel',
            name='categoria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campanamodel',
            name='tipo_impacto',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
