# Generated by Django 6.0.2 on 2026-02-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_alter_campanamodel_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriamodel',
            name='beneficios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='convocatoriamodel',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20),
        ),
    ]
