# Generated by Django 6.0.2 on 2026-02-19 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0008_alter_usuariomodel_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='en_revision', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('historial_estados', models.JSONField(blank=True, default=list)),
                ('convocatoria', models.ForeignKey(db_column='id_convocatoria', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='persistence.convocatoriamodel')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'postulacion',
                'ordering': ['-fecha_postulacion'],
                'managed': True,
                'unique_together': {('usuario', 'convocatoria')},
            },
        ),
    ]
