# Generated by Django 6.0.2 on 2026-03-01 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0009_postulacionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información')], default='info', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
