# Generated by Django 6.0.2 on 2026-03-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_notificacionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionmodel',
            name='referencia_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
