# Generated by Django 6.0.2 on 2026-03-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_notificacionmodel_referencia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionmodel',
            name='match_disponibilidad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulacionmodel',
            name='match_habilidades',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
