# Generated by Django 6.0.2 on 2026-03-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_postulacionmodel_match_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoriamodel',
            name='link_google_maps',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
