# Generated by Django 6.0.2 on 2026-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0013_convocatoriamodel_link_google_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanamodel',
            name='video_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
