# Generated by Django 6.0.2 on 2026-03-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0014_campanamodel_video_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
